# Generated by Django 4.2.1 on 2026-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OGVSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('home_lc', models.CharField(blank=True, max_length=100, null=True)),
                ('home_mc', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_programmes', models.CharField(blank=True, max_length=100, null=True)),
                ('synced_to_podio', models.BooleanField(default=False)),
            ],
        ),
    ]
