# Generated by Django 4.2.1 on 2026-03-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expa_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogvsignup',
            name='backgrounds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ogvsignup',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ogvsignup',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ogvsignup',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
