# Generated by Django 6.0.3 on 2026-03-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expa_data', '0002_ogvsignup_backgrounds_ogvsignup_campus_ogvsignup_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('signuped_at', models.DateTimeField(blank=True, null=True)),
                ('experience_end_date', models.DateTimeField(blank=True, null=True)),
                ('date_matched', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_realized', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_photo', models.URLField(blank=True, max_length=1000, null=True)),
                ('home_lc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_mc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('opportunity_title', models.CharField(blank=True, max_length=500, null=True)),
                ('opportunity_duration', models.IntegerField(blank=True, null=True)),
                ('opportunity_earliest_start_date', models.DateField(blank=True, null=True)),
                ('opportunity_latest_end_date', models.DateField(blank=True, null=True)),
                ('programme_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('programme_id', models.CharField(blank=True, max_length=50, null=True)),
                ('home_lc_name_opportunity', models.CharField(blank=True, max_length=255, null=True)),
                ('home_mc_name_opportunity', models.CharField(blank=True, max_length=255, null=True)),
                ('host_lc_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expa_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('date_opened', models.DateTimeField(blank=True, null=True)),
                ('applicants_count', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('programme_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sdg_target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slots', models.JSONField(blank=True, default=list, null=True)),
                ('available_slots_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SignupPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('profile_photo', models.URLField(blank=True, max_length=1000, null=True)),
                ('home_lc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_mc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_programmes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
