# Generated by Django 6.0.3 on 2026-03-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expa_data', '0004_igtaapplication_igtaopportunity_igteapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expaapplication',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igtaapplication',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igteapplication',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igvapplication',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
