# Generated by Django 6.0.3 on 2026-03-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expa_data', '0005_expaapplication_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igtaapplication',
            options={'verbose_name': 'IGTa Application', 'verbose_name_plural': 'IGTa Applications'},
        ),
        migrations.AlterModelOptions(
            name='igtaopportunity',
            options={'verbose_name': 'IGTa Opportunity', 'verbose_name_plural': 'IGTa Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='igteapplication',
            options={'verbose_name': 'IGTe Application', 'verbose_name_plural': 'IGTe Applications'},
        ),
        migrations.AlterModelOptions(
            name='igteopportunity',
            options={'verbose_name': 'IGTe Opportunity', 'verbose_name_plural': 'IGTe Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='igvapplication',
            options={'verbose_name': 'IGV Application', 'verbose_name_plural': 'IGV Applications'},
        ),
        migrations.AlterModelOptions(
            name='igvopportunity',
            options={'verbose_name': 'IGV Opportunity', 'verbose_name_plural': 'IGV Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='ogtasignup',
            options={'verbose_name': 'OGTa Signup', 'verbose_name_plural': 'OGTa Signups'},
        ),
        migrations.AlterModelOptions(
            name='ogtesignup',
            options={'verbose_name': 'OGTe Signup', 'verbose_name_plural': 'OGTe Signups'},
        ),
        migrations.AlterModelOptions(
            name='ogvsignup',
            options={'verbose_name': 'OGV Signup', 'verbose_name_plural': 'OGV Signups'},
        ),
        migrations.AddField(
            model_name='igtaopportunity',
            name='approvals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='igteopportunity',
            name='approvals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='igvopportunity',
            name='approvals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='approvals_count',
            field=models.IntegerField(default=0),
        ),
    ]
